#################################################################
###################### NexT Configuration #######################
#################################################################


# Allow to cache content generation. Introduced in NexT v6.0.0.
#cache:
#  enable: false
# Remove unnecessary files after hexo generate.
#minify: false

# ============================================================= #
# ============= i18n Settings ============= #
# ============================================================= #
#language_switcher: false
# ============================================================= #
# ============= Theme Core Configuration Settings ============= #
# ============================================================= #

custom_file_path:
  #sidebar: source/_data/sidebar.njk
  #footer: source/_data/footer.njk
  variable: source/_data/variables.styl
  style: source/_data/styles.styl


# ============================================================= #
# ====================== Scheme Settings ====================== #
# ============================================================= #

#scheme: Muse
#scheme: Mist
#scheme: Pisces
scheme: Gemini

darkmode: true


# ============================================================= #
# ================= Site Information Settings ================= #
# ============================================================= #
# 若使用主题自带的，将此项去掉
favicon:
  small: /images/favicon/favicon-32x32.png
  medium: /images/favicon/favicon-64x64.png
  apple_touch_icon: /images/favicon/apple-touch-icon.png
  safari_pinned_tab: /images/favicon/favicon-64x64.png
  #safari_pinned_tab: /images/favicon/logo.svg

creative_commons:
  license: by-nc-sa
  sidebar: false #侧边拦显示
  post: false #文章底部是否显示

# ============================================================= #
# ======================= Menu Settings ======================= #
# ============================================================= #

menu:
  home: / || fa fa-bell
  #html模式===================================================== #
  #nav: https://bingoyb.github.io/website-navigation ||fa fa-life-ring
  # Docs:
  #   default: /docs/ || fa fa-book
  #   Image: /image.html || fa fa-camera
  #   Audio Video: /audio_video.html || fa fa-music 
  #   nav: /nav.html || fa fa-life-ring
  #html模式===================================================== #
  Nav:
    default: /navs/ || fa fa-bars
    
    #=========================开发================================== #
    Develop: 
      default: /develop/ || fa fa-server
      Tools: /tools.html || fa 
      Dict: /dict.html
      Mirror: /mirror.html
      Basic: /Basic.html || fa 
      HarmonyOS: /HarmonyOS.html || fa 
      Android: /android.html || fa  
      IOS: /ios.html || fa 
      Flutter: /flutter.html 
      React Native: /ReactNative.html 
      Java: /java.html
      WEB: /web.html
      C#: /csharp.html
      Opex: /opex.html
      VersionControl: /versionControl.html
      OpenAPI: /openAPI.html
      AI: /ai.html
      Uni-app: /uni-app.html
      Cocos: /Cocos.html
      Unity: /unity.html
      Vue: /vue.html
      React: /react.html 
      JS: /js.html
      Res: /resources.html
      Data Structure: /DataStructure.html
      AV: /av.html
      Go: /go.html
      Crack: /crack.html
      Unrealengine: /unrealengine.html
      Xamarin: /Xamarin.html
      Rust: /Rust.html
    Course:
      default: /course/ || fa fa-podcast
    Image: 
      default: /image/ || fa fa-camera
    Langs: 
      default: /langs/ || fa fa-language
    AV: 
      default: /av/ || fa fa-film  
      Online: /online.html
      Vip: /vip.html
      4K: /4k.html
      FanJu: /fanju.html 
      ZiMu: /zimu.html
      BT: /bt.html
      BT_Tools: /bt_tools.html
      Pan: /pan.html
    AI:
      default: /ai/ || fa fa-info-circle
      ChatGPT: /ChatGPT.html
      NewBing: /newbing.html
      Leonardo: /Leonardo.html
      YiYan: /yiyan.html
      AIFace: /ai-face.html
      TongYi: /tongyi.html
      HuggingFace: /huggingface.html
    Nav: 
      default: /nav/ || fa fa-bars
      use: /use.html || fa 
    Resource:
      default: /resource/ || fa fa-gift
      PanAli: /pan-ali.html
      PanBaidu: /pan-baidu.html
      BT-Search: /bt-search.html
      BT-News: /bt-news.html
    SoftWare:
      default: /software/ || fa fa-desktop 
      Android: /Android.html
      IOS: /IOS.html
      Windows: /Windows.html 
      Mac: /Mac.html
      download: /download.html
      VPN: /VPN.html
      Plugin: /plugin.html
      TV: /tv.html
      PaySoftWare: /paysoftware.html
    Tools:
      default: /tools/ || fa fa-briefcase 
    Work: 
      default: /work/ || fa fa-file-word
    Resume: 
      default: /resume/ || fa fa-file-word
    InterView: 
      default: /interview/ || fa fa-file-word
      Flutter: /flutter.html || fa
      Android: /android.html || fa
      IOS: /ios.html ||fa
      Java: /java.html ||fa
      Net: /net.html ||fa
      DataStruct: /datastruct.html ||fa
      Web: /web.html
    WebSite: 
      default: /web/ || fa fa-at   
 
  #Plugins: /plugins/ || fa fa-flask
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #tags: /tags/ || fa fa-tags
  links: /links/ || fa fa-link  #add 2020-10-28
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat
  #Resume: /resume/ || fa fa-file-word  #add 2021-11-26 个人简历


menu_settings:
  icons: true
  badges: true


# ============================================================= #
# ===================== Sidebar Settings ====================== #
# ============================================================= #

sidebar:
  position: left
  display: post
  padding: 18
  offset: 12

avatar:
  url: /images/avatar.jpg
  rounded: true

social: #modify
  #GitHub: https://github.com/PGzxc || fab fa-github
  CSDN: http://blog.csdn.net/calvin_zhou || fa fa-book
  微博: http://weibo.com/5582039920 || fab fa-weibo
  简书: http://www.jianshu.com/u/c5cdcb4dc52b || fa fa-heartbeat
  #GitHub: https://github.com/next-theme || fab fa-github
  #E-Mail: mailto:support@theme-next.org || fa fa-envelope
  #RSS: /atom.xml || fa fa-rss
  #Gitter: https://gitter.im/hexo-next || fab fa-gitter

social_icons:
  enable: true
  icons_only: true
  transition: true

toc:
  enable: true
  number: true
  wrap: true


# ============================================================= #
# ====================== Footer Settings ====================== #
# ============================================================= #

footer:
  since: 2017 #modify 2020-10-29
  icon:
    name: fa fa-heart
    animated: true
    color: "#808080"
  copyright: 
  powered: false
  # Beian ICP and gongan information for Chinese users. See: https://beian.miit.gov.cn, http://www.beian.gov.cn
  beian:
    enable: false
    icp: 京ICP备18061062号-1
    gongan_id: 
    gongan_num: 
    gongan_icon_url: 

# ============================================================= #
# ======================= Post Settings ======================= #
# ============================================================= #

post_meta:
  updated_at:
    enable: false

symbols_count_time:
  separated_meta: true
  item_text_total: true

post_edit:
  enable: true
  url: https://github.com/PGzxc/PGzxc.github.io/edit/master/source/


# ============================================================= #
# ==================== Misc Theme Settings ==================== #
# ============================================================= #

mobile_layout_economy: true

codeblock:
  theme:
    light: an-old-hope
    dark: an-old-hope
    # light: default
    # dark: tomorrow-night
  copy_button:
    enable: true
    style: default

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

github_banner:
  enable: false
  permalink: https://github.com/PGzxc/PGzxc.github.io #modify
  title: Fork Me on GitHub

font:
  enable: true
  codes:
    external: true
    family: Inconsolata

# ============================================================= #
# ============================ 统计 =========================== #
# ============================================================= #

leancloud_visitors: #827489398@qq.com 未实名认证，不可用
  enable: false
  app_id: xoStNXjq2xNoDRjTltoOztdq-gzGzoHsz
  app_key: 6g89MPFNvTH2YHnKMAK1n1V8
  server_url: # <your server url>
  security: true

busuanzi_count:
  enable: false
  total_visitors: false
  total_visitors_icon: fa fa-user
  total_views: false
  total_views_icon: fa fa-eye
  post_views: false
  post_views_icon: fa fa-eye

# ============================================================= #
# ======================= SEO Settings ======================== #
# ============================================================= #

index_with_subtitle: true

exturl: false

google_site_verification: 

# ============================================================= #
# =================== Comments and Widgets ==================== #
# ============================================================= #

comments:
  lazyload: true

#livere_uid: MTAyMC8zMjQ1OC85MDE5 #modify
gitalk:
  enable: true
  github_id: PGzxc # GitHub repo owner
  repo: PGzxc.github.io # Repository name to store issues
  client_id: 4d2d97c55a316dfcea73 # GitHub Application Client ID
  client_secret: f55fe43764e8560484a13850e4a6d84792924fb0 # GitHub Application Client Secret
  admin_user: PGzxc # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
  distraction_free_mode: true # Facebook-like distraction free mode
  language: zh-CN
valine:
  enable: false
  appId: xoStNXjq2xNoDRjTltoOztdq-gzGzoHsz # Your leancloud application appid
  appKey: 6g89MPFNvTH2YHnKMAK1n1V8 # Your leancloud application appkey
  serverURLs: http://localhost:7000 # When the custom domain name is enabled, fill it in here
  placeholder: Just go go # Comment box placeholder
  avatar: mm # Gravatar style
  meta: [nick, mail, link] # Custom comment header
  pageSize: 10 # Pagination size
  lang: # Language, available values: en, zh-cn
  visitor: false # Article reading statistic
  comment_count: true # If false, comment count will only be displayed in post page, not in home page
  recordIP: false # Whether to record the commenter IP
  enableQQ: false # Whether to enable the Nickname box to automatically get QQ Nickname and QQ Avatar
  requiredFields: [] # Set required fields: [nick] | [nick, mail]
# ============================================================= #
# ================= Statistics and Analytics ================== #
# ============================================================= #

# google_analytics:
#   tracking_id: 


# ============================================================= #
# ====================== Search Services ====================== #
# ============================================================= #

local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1

# ============================================================= #
# ======================= Chat Services ======================= #
# ============================================================= #
#注册地址：https://gitter.im

gitter:
  enable: true
  room: PGzxc/community

# ============================================================= #
# ======================== Tag Plugins ======================== #
# ============================================================= #

note:
  style: simple
  icons: true
  light_bg_offset: -3

tabs:
  transition:
    tabs: true
    labels: true

mermaid:
  enable: true

wavedrom:
  enable: true

# ============================================================= #
# ==================== External Libraries ===================== #
# ============================================================= #

math:
  mathjax:
    enable: true
    tags: ams

pjax: true

mediumzoom: true
#fancybox: true
#lazyload: true
#pangu: false

motion:
  async: true

# ============================================================= #
# ======================= CDN Settings ======================== #
# ============================================================= #

vendors:
  internal: local
  plugins: cdnjs
