language: en
root: /en/
source_dir: source-en
public_dir: public/en

# 菜单翻译（左侧导航英文版）
menu:
  home: / || fa fa-bell
  Nav:
    default: /navs/ || fa fa-bars
  Course: /course/ || fa fa-podcast
  Image: /image/ || fa fa-camera
  Langs: /langs/ || fa fa-language
  AV: /av/ || fa fa-film
  AI: /ai/ || fa fa-info-circle
  Resource: /resource/ || fa fa-gift
  SoftWare: /software/ || fa fa-desktop
  Tools: /tools/ || fa fa-briefcase
  Work: /work/ || fa fa-file-word
  Resume: /resume/ || fa fa-file-word
  InterView: /interview/ || fa fa-file-word
  WebSite: /web/ || fa fa-at
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  links: /links/ || fa fa-link

# 其他覆盖
title: PGzxc (English)
subtitle: What I learn from books is superficial; I must experience it myself

server:
  port: 7700