title: PGzxc (Japanese)
subtitle: 本から学んだことは表面的なもの；自分で体験しなければならない
description: ''
keywords: ''
author: PGzxc
language: ja
language_switcher: false
i18n_dir: ':lang'
timezone: Asia/Shanghai
url: https://pgzxc.github.io/
root: /ja/
permalink: posts/:abbrlink.html
abbrlink:
  alg: crc32
  rep: hex
permalink_defaults:
  lang: zh-CN
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source-ja
public_dir: public/ja
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
skip_render:
  - robots.txt
  - animate/*
  - highlight/*
  - resume/_parts/**
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  per_page: 5
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: []
exclude: []
ignore: []
theme: next
archive_generator:
  per_page: 12
  yearly: true
  monthly: true
  daily: false
server:
  port: 7700
marked:
  smartypants: false
  lazyload: true
search:
  path: search.json
  field: post
  content: false
  format: html
symbols_count_time:
  symbols: false
  time: true
  total_symbols: false
  total_time: false
  exclude_codeblock: false
  awl: 4
  wpm: 275
  suffix: mins.
encrypt:
  abstract: 有东西被加密了, 请输入密码查看.
  message: 您好, 这里需要密码.
  tags:
    - name: tagName
      password: 密码A
    - name: tagName
      password: 密码B
  template: >-
    <div id="hexo-blog-encrypt" data-wpm="{{hbeWrongPassMessage}}"
    data-whm="{{hbeWrongHashMessage}}"><div class="hbe-input-container"><input
    type="password" id="hbePass" placeholder="{{hbeMessage}}"
    /><label>{{hbeMessage}}</label><div class="bottom-line"></div></div><script
    id="hbeData" type="hbeData"
    data-hmacdigest="{{hbeHmacDigest}}">{{hbeEncryptedData}}</script></div>
  wrong_pass_message: 抱歉, 这个密码看着不太对, 请再试试.
  wrong_hash_message: 抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容.
deploy:
  type: git
  repo:
    github: git@github.com:PGzxc/PGzxc.github.io.git,hexo
    coding:
      url: git@e.coding.net:pgzxc/pgzxc/pgzxc.git
      branch: hexo
menu:
  home: / || fa fa-bell
  Nav:
    default: /navs/ || fa fa-bars
  Course: /course/ || fa fa-podcast
  Image: /image/ || fa fa-camera
  Langs: /langs/ || fa fa-language
  AV: /av/ || fa fa-film
  AI: /ai/ || fa fa-info-circle
  Resource: /resource/ || fa fa-gift
  SoftWare: /software/ || fa fa-desktop
  Tools: /tools/ || fa fa-briefcase
  Work: /work/ || fa fa-file-word
  Resume: /resume/ || fa fa-file-word
  InterView: /interview/ || fa fa-file-word
  WebSite: /web/ || fa fa-at
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  links: /links/ || fa fa-link
